export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#ffffff',
          50: '#fafafa', 100: '#f5f5f5', 200: '#e5e5e5',
          300: '#d4d4d4', 400: '#a3a3a3', 500: '#737373',
          600: '#525252', 700: '#404040', 800: '#262626', 900: '#171717',
          container: '#e2e2e2',
          fixed: '#e2e2e2',
          'fixed-dim': '#c6c6c7',
        },
        secondary: {
          DEFAULT: '#c8c6c5',
          container: '#474746',
          fixed: '#e5e2e1',
          'fixed-dim': '#c8c6c5',
        },
        tertiary: {
          DEFAULT: '#ffffff',
          container: '#e5e2e1',
          fixed: '#e5e2e1',
          'fixed-dim': '#c9c6c5',
        },
        surface: {
          DEFAULT: '#121414',
          50: '#e3e2e2',
          100: '#c4c7c8',
          200: '#8e9192',
          300: '#444748',
          400: '#383939', 
          500: '#343535', 
          600: '#292a2a', 
          700: '#1f2020', 
          800: '#1b1c1c', 
          900: '#121414', 
          950: '#0d0e0f', 
          black: '#000000',
          bright: '#383939',
          variant: '#343535',
          dim: '#121414',
          tint: '#c6c6c7',
          container: '#1f2020',
          'container-lowest': '#0d0e0f',
          'container-low': '#1b1c1c',
          'container-high': '#292a2a',
          'container-highest': '#343535',
        },
        error: {
          DEFAULT: '#ffb4ab',
          container: '#93000a',
        },
        on: {
          background: '#e3e2e2',
          surface: '#e3e2e2',
          'surface-variant': '#c4c7c8',
          primary: '#2f3131',
          'primary-container': '#636565',
          'primary-fixed': '#1a1c1c',
          'primary-fixed-variant': '#454747',
          secondary: '#313030',
          'secondary-container': '#b7b5b4',
          'secondary-fixed': '#1c1b1b',
          'secondary-fixed-variant': '#474746',
          tertiary: '#313030',
          'tertiary-container': '#656464',
          'tertiary-fixed': '#1c1b1b',
          'tertiary-fixed-variant': '#474646',
          error: '#690005',
          'error-container': '#ffdad6',
        },
        inverse: {
          surface: '#e3e2e2',
          'on-surface': '#303031',
          primary: '#5d5f5f',
        },
        background: '#121414',
        outline: {
          DEFAULT: '#8e9192',
          variant: '#444748',
        },
        glass: {
          light: 'rgba(255,255,255,0.03)',
          border: 'rgba(255,255,255,0.08)',
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      backdropBlur: { xs: '2px' },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'fade-up': 'fadeUp 0.4s ease-out',
        'fade-down': 'fadeDown 0.3s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'marquee-left': 'marqueeLeft 40s linear infinite',
        'marquee-right': 'marqueeRight 40s linear infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeUp: { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeDown: { from: { opacity: '0', transform: 'translateY(-16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(24px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        slideInLeft: { from: { opacity: '0', transform: 'translateX(-24px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer: { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        glow: { from: { boxShadow: '0 0 10px rgba(59,130,246,0.3)' }, to: { boxShadow: '0 0 25px rgba(59,130,246,0.6)' } },
        marqueeLeft: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-100%)' } },
        marqueeRight: { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
      },
      boxShadow: {
        'glass': '0 20px 40px rgba(0,0,0,0.5), inset 0 1px 1px rgba(255,255,255,0.1)',
        'glass-lg': '0 30px 60px rgba(0,0,0,0.6), inset 0 1px 1px rgba(255,255,255,0.15)',
        'card': '0 20px 40px rgba(0,0,0,0.4)',
        'card-hover': '0 24px 48px rgba(0,0,0,0.5)',
      },
      borderRadius: {
        'xl': '0.75rem',
        '2xl': '1rem', 
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      spacing: {
        "section-gap": "80px",
        "edge-margin": "40px",
        "edge-margin-mobile": "20px",
        "stack-lg": "24px",
        "stack-xs": "4px",
        "container-max": "1440px",
        "stack-md": "16px",
        "stack-sm": "8px",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Hanken Grotesk', 'sans-serif'],
        mono: ['Geist', 'monospace'],
        "display-lg-mobile": ["Hanken Grotesk"],
        "label-mono": ["Geist", "monospace"],
        "display-lg": ["Hanken Grotesk"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600"}],
        "label-mono": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400"}]
      },
    },
  },
  plugins: [],
}
