import React from 'react';
import Card from '../components/common/Card';

const Insights = () => {
  return (
    <div className="space-y-6">
      <Card title="AI Powered Insights">
        <p className="text-gray-400">Get intelligent insights generated by Gemini AI.</p>
      </Card>
    </div>
  );
};

export default Insights;
